# Generated by Django 5.0.6 on 2024-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(unique=True),
        ),
    ]
