# Generated by Django 5.0.6 on 2024-06-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
